default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  reconnect: true
  encoding: unicode

development:
  <<: *default
  database: todos_api

test:
  <<: *default
  database: todos_api_test
