development:
  adapter: postgresql
  encoding: unicode
  database: todos_api 
  username: root
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: todos_api_test
  username: root
  password:
  host: localhost
